# .air.toml

# 監控的目錄
root = "."
tmp_dir = "tmp" # 用來存儲臨時文件的目錄
color = "true" # 是否啟用顏色

[build]
  cmd = "go build -o tmp/main ."
  bin = "tmp/main" # 可執行文件的輸出位置
  include_ext = ["go"] # 監控的文件擴展名
  exclude_dir = ["assets", "vendor"] # 排除的目錄

[watch]
  include_ext = ["go"]
  exclude_dir = ["assets", "vendor"] # 排除的目錄
