// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/deleteUser": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "使用者提供帳號與密碼後刪除使用者",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "使用者刪除",
                "parameters": [
                    {
                        "description": "使用者資料（Email \u0026 Password ＆ Platform）",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/account.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登入成功，返回 JWT Token 和成功訊息",
                        "schema": {
                            "$ref": "#/definitions/model.RequestMessage"
                        }
                    },
                    "400": {
                        "description": "無效的輸入資料",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorRequest"
                        }
                    },
                    "401": {
                        "description": "密碼錯誤",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorRequest"
                        }
                    },
                    "404": {
                        "description": "使用者不存在",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorRequest"
                        }
                    },
                    "500": {
                        "description": "系統錯誤或 JWT 簽發失敗",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorRequest"
                        }
                    }
                }
            }
        },
        "/api/v1/login": {
            "post": {
                "description": "使用者提供帳號與密碼後登入系統，並取得 JWT Token。登入成功後會設置 session cookie 並返回 JWT token。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "使用者登入",
                "parameters": [
                    {
                        "description": "登入資料（Email \u0026 Password）",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/account.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登入成功，返回 JWT Token 和成功訊息",
                        "schema": {
                            "$ref": "#/definitions/account.UserRequest"
                        }
                    },
                    "400": {
                        "description": "無效的輸入資料",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorRequest"
                        }
                    },
                    "401": {
                        "description": "密碼錯誤",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorRequest"
                        }
                    },
                    "404": {
                        "description": "使用者不存在",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorRequest"
                        }
                    },
                    "500": {
                        "description": "系統錯誤或 JWT 簽發失敗",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorRequest"
                        }
                    }
                }
            }
        },
        "/api/v1/register": {
            "post": {
                "description": "新用戶註冊功能，包含基本資料驗證、密碼加密、JWT Token 生成和 Session 設置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "使用者註冊",
                "parameters": [
                    {
                        "description": "註冊資料（Email、Password、Name、Birthday、Permission、Platform）",
                        "name": "Register",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/account.Register"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "註冊成功，返回 JWT Token 和成功訊息",
                        "schema": {
                            "$ref": "#/definitions/account.UserRequest"
                        }
                    },
                    "400": {
                        "description": "無效的輸入資料或帳號已存在",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorRequest"
                        }
                    },
                    "500": {
                        "description": "系統錯誤或 JWT 簽發失敗",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorRequest"
                        }
                    }
                }
            }
        },
        "/api/v1/sendmessage": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "使用者傳送訊息，需要 JWT Token 驗證",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Message"
                ],
                "summary": "傳送訊息",
                "parameters": [
                    {
                        "description": "訊息資料",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/message_model.MessageData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "訊息送出成功",
                        "schema": {
                            "$ref": "#/definitions/message_model.MessageRequest"
                        }
                    },
                    "400": {
                        "description": "輸入資料格式錯誤",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorRequest"
                        }
                    },
                    "401": {
                        "description": "未授權，缺少或無效的 JWT Token",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorRequest"
                        }
                    },
                    "500": {
                        "description": "伺服器內部錯誤",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorRequest"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "account.Register": {
            "type": "object",
            "properties": {
                "Email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "bethday": {
                    "type": "string",
                    "example": "2025-03-23T15:04:05-00:00"
                },
                "name": {
                    "type": "string",
                    "example": "kent"
                },
                "password": {
                    "type": "string",
                    "example": "yourpassword"
                },
                "permission": {
                    "type": "integer",
                    "example": 1
                },
                "platform": {
                    "type": "string",
                    "example": "App"
                }
            }
        },
        "account.User": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "yourpassword"
                },
                "platform": {
                    "type": "string",
                    "example": "App"
                }
            }
        },
        "account.UserRequest": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Login successful"
                },
                "token": {
                    "type": "string",
                    "example": "example-jwt-token"
                }
            }
        },
        "message_model.MessageData": {
            "type": "object",
            "properties": {
                "Detail": {
                    "type": "string",
                    "example": "Detail"
                },
                "Subtile": {
                    "type": "string",
                    "example": "Subtile"
                },
                "Title": {
                    "type": "string",
                    "example": "Test"
                }
            }
        },
        "message_model.MessageRequest": {
            "type": "object",
            "properties": {
                "Message": {
                    "type": "string",
                    "example": "Sucessful send Message"
                }
            }
        },
        "model.ErrorRequest": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "error"
                }
            }
        },
        "model.RequestMessage": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Community_Notification_System",
	Description:      "Community_Notification_System",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
